name = "ReplaceBuildMode"
uid = "8232b0ea-6b15-46a8-839f-843e89edc377"
version = 1
copyright = "no"
description = "Makes it more obvious, visually, when you are in build mode, adds custom exit build mode key, implemented as copy and modify of whole buildmode.lua"
author = "Thomas Young"
url = "upcoder.com"
selectable = true
enabled = true
exclusive = false
ui_only = true
requires = {}
requiresNames = {}
conflicts = {}
before = {}
after = {}
