-- ui_lua import('/mods/UnitInfoToLog/main.lua').InfoToLog()
-- ui_lua import('/mods/UnitInfoToLog/main.lua').BluePrintToLog()

function LogInfoFor(e)
    LOG("Unit selected with ID: "..e:GetEntityId())
    LOG("GetEconData() returns:"..repr(e:GetEconData()))
    LOG("GetMissileInfo() returns:"..repr(e:GetMissileInfo()))
	LOG("GetFireState() returns:"..repr(GetFireState({e})))
    LOG("GetCommandQueue() returns:"..repr(e:GetCommandQueue()))
    --LOG("GetGuardedEntity() returns:"..repr(e:GetGuardedEntity())) -- looks like this causes a hard crash, when there is one!
    if e:GetGuardedEntity() then
        LOG("Has a guarded entity")
    end
    if e:GetCreator() then
        LOG("Has a creator")
    end
    Units = import('/mods/common/units.lua')
    if Units.being_built[e:GetEntityId()] then
        if Units.being_built[e:GetEntityId()] == e then
            LOG("Being built")
        else
            LOG("Units.being_built is not consistent")
        end
    end
    LOG("GetFootPrintSize() returns:"..repr(e:GetFootPrintSize()))
    LOG("GetBuildRate() returns:"..repr(e:GetBuildRate()))
    LOG("GetWorkProgress() returns:"..repr(e:GetWorkProgress()))
    LOG("GetSelectionSets() returns:"..repr(e:GetSelectionSets()))
    LOG("Categories:"..repr(e:GetBlueprint().Categories))
    LOG("IsIdle() returns:"..repr(e:IsIdle()))  
    LOG("IsAutoMode() returns:"..repr(e:IsAutoMode()))  
    LOG("IsInCategory('TECH1') returns:"..repr(e:IsInCategory('TECH1')))
    --LOG("GetWorkProgess() returns:"..repr(e:GetWorkProgess())) -- generates error: attempt to call method `GetWorkProgess' (a nil value)
    LOG("================")
end

function InfoToLog()
    local t = GetSelectedUnits()
    if not t or not t[1] then
        return
    end
    local e = t[1]
    LOG("================")
    LOG("Game tick = "..GameTick())
    LOG("Selected unit:")
    LogInfoFor(e)
    local focus = e:GetFocus()
    if focus and not focus:IsDead() then
        LOG("Focus:")
        LogInfoFor(focus)
    end
end

function BluePrintToLog()
    local t = GetSelectedUnits()
    if not t or not t[1] then
        return
    end
    local e = t[1]
    LOG("================")
    LOG("Game tick = "..GameTick())
    LOG("Blueprint for selected unit:")
    LOG(repr(e:GetBlueprint()))
    LOG("================")
end

--[[
INFO: GetEconData() returns:{
INFO:   energyConsumed=0,
INFO:   energyProduced=0,
INFO:   energyRequested=0,
INFO:   massConsumed=0,
INFO:   massProduced=0,
INFO:   massRequested=0
INFO: }
INFO: GetCommandQueue() returns:{
INFO:   {
INFO:     position={ <metatable=table: 1A0E8DE8>
INFO:       157.19039916992,
INFO:       14.826637268066,
INFO:       144.65634155273
INFO:     },
INFO:     type="Move"
INFO:   },
INFO:   {
INFO:     position={ <metatable=table: 1A0E8DE8>
INFO:       151.3240814209,
INFO:       14.849033355713,
INFO:       152.37687683105
INFO:     },
INFO:     type="Move"
INFO:   },
INFO:   {
INFO:     position={ <metatable=table: 1A0E8DE8>
INFO:       158.18643188477,
INFO:       14.783630371094,
INFO:       154.50886535645
INFO:     },
INFO:     type="Move"
INFO:   },
INFO:   {
INFO:     position={ <metatable=table: 1A0E8DE8>
INFO:       160.0930480957,
INFO:       14.762691497803,
INFO:       155.28187561035
INFO:     },
INFO:     type="AggressiveMove"
INFO:   }
INFO: }
]]--

-- ** Cybran commander blueprint dump:
--[[
INFO: {
INFO:   AI={
INFO:     AttackAngle=0,
INFO:     AutoSurfaceToAttack=true,
INFO:     BeaconName="",
INFO:     GuardFormationName="GuardFormation",
INFO:     GuardRadius=10,
INFO:     GuardReturnRadius=50,
INFO:     GuardScanRadius=31.5,
INFO:     InitialAutoMode=false,
INFO:     NeedUnpack=false,
INFO:     RefuelingMultiplier=1,
INFO:     RefuelingRepairAmount=20,
INFO:     RepairConsumeEnergy=2,
INFO:     RepairConsumeMass=0.5,
INFO:     ShowAssistRangeOnSelect=false,
INFO:     StagingPlatformScanRadius=12,
INFO:     TargetBones={
INFO:       "Head",
INFO:       "Torso",
INFO:       "Right_Arm_B01",
INFO:       "Left_Arm_B01",
INFO:       "Back_Upgrade",
INFO:       "Left_Foot_B01",
INFO:       "Right_Foot_B01"
INFO:     }
INFO:   },
INFO:   Air={
INFO:     AutoLandTime=0,
INFO:     BankFactor=0.5,
INFO:     BankForward=false,
INFO:     BreakOffDistance=0,
INFO:     BreakOffIfNearNewTarget=false,
INFO:     BreakOffTrigger=0,
INFO:     CanFly=false,
INFO:     CirclingDirChange=true,
INFO:     CirclingElevationChangeRatio=0.25,
INFO:     CirclingFlightChangeFrequency=2,
INFO:     CirclingRadiusChangeMaxRatio=0.89999997615814,
INFO:     CirclingRadiusChangeMinRatio=0.60000002384186,
INFO:     CirclingRadiusVsAirMult=1,
INFO:     CirclingTurnMult=3,
INFO:     CombatTurnSpeed=1,
INFO:     EngageDistance=0,
INFO:     FlyInWater=false,
INFO:     HoverOverAttack=false,
INFO:     KLift=1,
INFO:     KLiftDamping=1,
INFO:     KMove=1,
INFO:     KMoveDamping=1,
INFO:     KRoll=3,
INFO:     KRollDamping=3,
INFO:     KTurn=3,
INFO:     KTurnDamping=3,
INFO:     LiftFactor=5,
INFO:     MaxAirspeed=0,
INFO:     MinAirspeed=0,
INFO:     PredictAheadForBombDrop=0,
INFO:     RandomBreakOffDistanceMult=1.5,
INFO:     RandomMaxChangeCombatStateTime=6,
INFO:     RandomMinChangeCombatStateTime=3,
INFO:     StartTurnDistance=3.6000001430511,
INFO:     SustainedTurnThreshold=10,
INFO:     TightTurnMultiplier=1,
INFO:     TransportHoverHeight=0,
INFO:     TurnSpeed=1,
INFO:     Winged=false
INFO:   },
INFO:   AltFootprint={
INFO:     Flags=0,
INFO:     MaxSlope=0.75,
INFO:     MinWaterDepth=0,
INFO:     OccupancyCaps=3,
INFO:     SizeX=1,
INFO:     SizeZ=1
INFO:   },
INFO:   Audio={
INFO:     CaptureLoop=userdata: CSndParams* at 1FC48F4C = [CSndParams at 0x15341460],
INFO:     CommanderArrival=userdata: CSndParams* at 1FC48F24 = [CSndParams at 0x15341500],
INFO:     Construct=userdata: CSndParams* at 1FC484AC = [CSndParams at 0x153415A0],
INFO:     ConstructLoop=userdata: CSndParams* at 1FC48FC4 = [CSndParams at 0x1534FB40],
INFO:     EnhanceEnd=userdata: CSndParams* at 1FC48FB0 = [CSndParams at 0x1267C5F0],
INFO:     EnhanceFail=userdata: CSndParams* at 1FC48240 = [CSndParams at 0x1267CFA0],
INFO:     EnhanceLoop=userdata: CSndParams* at 1FC483E4 = [CSndParams at 0x1267C640],
INFO:     EnhanceStart=userdata: CSndParams* at 1FC48484 = [CSndParams at 0x1267CB40],
INFO:     FootFallGeneric=userdata: CSndParams* at 1FC48650 = [CSndParams at 0x1534FD20],
INFO:     FootFallGenericSeabed=userdata: CSndParams* at 1FC48F74 = [CSndParams at 0x1534FDC0],
INFO:     Killed=userdata: CSndParams* at 1FC48434 = [CSndParams at 0x1534FE60],
INFO:     ReclaimLoop=userdata: CSndParams* at 1FC48F9C = [CSndParams at 0x1534FF00],
INFO:     StartCapture=userdata: CSndParams* at 1FC483A8 = [CSndParams at 0x1534FFA0],
INFO:     StartMove=userdata: CSndParams* at 1FC48448 = [CSndParams at 0x1534F640],
INFO:     StartReclaim=userdata: CSndParams* at 1FC48F88 = [CSndParams at 0x1534F6E0],
INFO:     StopMove=userdata: CSndParams* at 1FC48420 = [CSndParams at 0x1534F780],
INFO:     TeleportChargingAtDestination=userdata: CSndParams* at 1FC48F60 = [CSndParams at 0x1534F820],
INFO:     TeleportChargingAtUnit=userdata: CSndParams* at 1FC48FD8 = [CSndParams at 0x1534F8C0],
INFO:     TeleportIn=userdata: CSndParams* at 1FC4845C = [CSndParams at 0x1534F960],
INFO:     UISelection=userdata: CSndParams* at 1FC4818C = [CSndParams at 0x1534FA00]
INFO:   },
INFO:   AverageDensity=0.49000000953674,
INFO:   BlueprintId="url0001",
INFO:   BlueprintOrdinal=3512,
INFO:   Buffs={ Regen={ Level1=4, Level2=8, Level3=12, Level4=16, Level5=20 } },
INFO:   Categories={
INFO:     "ENGINEER",
INFO:     "SELECTABLE",
INFO:     "LAND",
INFO:     "MASSFABRICATION",
INFO:     "MASSPRODUCTION",
INFO:     "OVERLAYOMNI",
INFO:     "DIRECTFIRE",
INFO:     "SHOWQUEUE",
INFO:     "ECONOMIC",
INFO:     "COMMAND",
INFO:     "PATROLHELPER",
INFO:     "OVERLAYMISC",
INFO:     "CYBRAN",
INFO:     "OVERLAYDIRECTFIRE",
INFO:     "VISIBLETORECON",
INFO:     "MOBILE",
INFO:     "PRODUCTSC1",
INFO:     "REPAIR",
INFO:     "CAPTURE",
INFO:     "ENERGYPRODUCTION",
INFO:     "RECLAIM",
INFO:     "CONSTRUCTION"
INFO:   },
INFO:   CategoriesHash={
INFO:     CAPTURE=true,
INFO:     COMMAND=true,
INFO:     CONSTRUCTION=true,
INFO:     CYBRAN=true,
INFO:     DIRECTFIRE=true,
INFO:     ECONOMIC=true,
INFO:     ENERGYPRODUCTION=true,
INFO:     ENGINEER=true,
INFO:     LAND=true,
INFO:     MASSFABRICATION=true,
INFO:     MASSPRODUCTION=true,
INFO:     MOBILE=true,
INFO:     OVERLAYDIRECTFIRE=true,
INFO:     OVERLAYMISC=true,
INFO:     OVERLAYOMNI=true,
INFO:     PATROLHELPER=true,
INFO:     PRODUCTSC1=true,
INFO:     RECLAIM=true,
INFO:     REPAIR=true,
INFO:     SELECTABLE=true,
INFO:     SHOWQUEUE=true,
INFO:     VISIBLETORECON=true
INFO:   },
INFO:   CollisionOffsetX=0,
INFO:   CollisionOffsetY=0,
INFO:   CollisionOffsetZ=0,
INFO:   CollisionShape="Box",
INFO:   Defense={
INFO:     AirThreatLevel=0,
INFO:     ArmorType="Commander",
INFO:     EconomyThreatLevel=5,
INFO:     Health=10000,
INFO:     MaxHealth=10000,
INFO:     RegenRate=15,
INFO:     Shield={ RegenAssistMult=1, ShieldSize=0 },
INFO:     SubThreatLevel=0,
INFO:     SurfaceThreatLevel=75
INFO:   },
INFO:   Description="<LOC url0001_desc>Armored Command Unit",
INFO:   DesiredShooterCap=3,
INFO:   Display={
INFO:     Abilities={
INFO:       "<LOC ability_amphibious>Amphibious",
INFO:       "<LOC ability_customizable>Customizable",
INFO:       "<LOC ability_engineeringsuite>Engineering Suite",
INFO:       "<LOC ability_notcap>Not Capturable",
INFO:       "<LOC ability_omni>Omni Sensor",
INFO:       "<LOC ability_deathaoe>Volatile"
INFO:     },
INFO:     AnimationWalk="/units/url0001/url0001_awalk02.sca",
INFO:     AnimationWalkRate=1.7000000476837,
INFO:     BuildMeshBlueprint="/units/url0001/url0001_mesh_build",
INFO:     CloakMeshBlueprint="/units/url0001/url0001_mesh_cloak",
INFO:     DisplayName="",
INFO:     HideLifebars=false,
INFO:     IconName="url0001",
INFO:     IdleEffects={
INFO:       Seabed={
INFO:         Effects={
INFO:           {
INFO:             Bones={
INFO:               "Left_Arm_B01",
INFO:               "Right_Arm_B01",
INFO:               "Turret_Muzzle_01",
INFO:               "Turret_Muzzle_02"
INFO:             },
INFO:             Type="UnderWater01"
INFO:           }
INFO:         }
INFO:       }
INFO:     },
INFO:     Mesh={
INFO:       BlueprintId="/units/url0001/url0001_mesh",
INFO:       BlueprintOrdinal=1976,
INFO:       Description="",
INFO:       IconFadeInZoom=130,
INFO:       LODs={
INFO:         {
INFO:           AlbedoName="/units/url0001/url0001_albedo.dds",
INFO:           LODCutoff=100,
INFO:           LookupName="",
INFO:           MeshName="/units/url0001/url0001_lod0.scm",
INFO:           NormalsName="/units/url0001/url0001_normalsTS.dds",
INFO:           Occlude=false,
INFO:           Scrolling=false,
INFO:           SecondaryName="",
INFO:           ShaderName="Insect",
INFO:           Silhouette=false,
INFO:           SpecularName="/units/url0001/url0001_SpecTeam.dds"
INFO:         },
INFO:         {
INFO:           AlbedoName="/units/url0001/url0001_lod1_albedo.dds",
INFO:           LODCutoff=215,
INFO:           LookupName="",
INFO:           MeshName="/units/url0001/url0001_lod1.scm",
INFO:           NormalsName="/units/url0001/url0001_normalsTS.dds",
INFO:           Occlude=false,
INFO:           Scrolling=false,
INFO:           SecondaryName="",
INFO:           ShaderName="Insect",
INFO:           Silhouette=false,
INFO:           SpecularName="/units/url0001/url0001_lod1_specteam.dds"
INFO:         }
INFO:       },
INFO:       SortOrder=0,
INFO:       Source="/units/url0001/url0001_unit.bp",
INFO:       StraddleWater=false,
INFO:       UniformScale=1
INFO:     },
INFO:     MeshBlueprint="/units/url0001/url0001_mesh",
INFO:     MeshBlueprintWrecked="/units/url0001/url0001_mesh_wreck",
INFO:     MovementEffects={
INFO:       Land={
INFO:         Effects={
INFO:           {
INFO:             Bones={ "Right_Footprint", "Left_Footprint" },
INFO:             Type="GroundKickup01"
INFO:           }
INFO:         },
INFO:         Footfall={
INFO:           Bones={
INFO:             {
INFO:               FootBone="Left_Footprint",
INFO:               HipBone="Left_Leg_B01",
INFO:               KneeBone="Left_Leg_B02",
INFO:               Tread={
INFO:                 TreadMarks="CommanderPrint_albedo",
INFO:                 TreadMarksSizeX=0.5,
INFO:                 TreadMarksSizeZ=0.5,
INFO:                 TreadOffset={ 0.15000000596046, 0, 0.44999998807907 }
INFO:               },
INFO:               Type="FootFall02"
INFO:             },
INFO:             {
INFO:               FootBone="Right_Footprint",
INFO:               HipBone="Right_Leg_B01",
INFO:               KneeBone="Right_Leg_B02",
INFO:               Tread={
INFO:                 TreadMarks="CommanderPrint_albedo",
INFO:                 TreadMarksSizeX=0.5,
INFO:                 TreadMarksSizeZ=0.5,
INFO:                 TreadOffset={ -0.15000000596046, 0, 0.44999998807907 }
INFO:               },
INFO:               Type="FootFall02"
INFO:             }
INFO:           }
INFO:         }
INFO:       },
INFO:       Seabed={
INFO:         Effects={
INFO:           {
INFO:             Bones={
INFO:               "Torso",
INFO:               "Left_Arm_B01",
INFO:               "Right_Arm_B01",
INFO:               "Turret_Muzzle_01",
INFO:               "Turret_Muzzle_02",
INFO:               "Left_Foot_B01",
INFO:               "Right_Foot_B01"
INFO:             },
INFO:             Type="UnderWater01"
INFO:           }
INFO:         }
INFO:       }
INFO:     },
INFO:     PlaceholderMeshName="UXB0000",
INFO:     SpawnRandomRotation=true,
INFO:     TeleportEffects={
INFO:       ChargeFxAtUnitBones={
INFO:         {
INFO:           Bone="Back_Upgrade",
INFO:           Offset={ 0, 0.050000000745058, 0.20000000298023 }
INFO:         }
INFO:       },
INFO:       PlayChargeFxAtDestination=true,
INFO:       PlayChargeFxAtUnit=true,
INFO:       PlayTeleportInFx=true,
INFO:       PlayTeleportOutFx=true
INFO:     },
INFO:     TransportAnimation={
INFO:       { Animation="/units/URL0001/URL0001_afold.sca", Weight=100 }
INFO:     },
INFO:     TransportDropAnimation={
INFO:       { Animation="/units/URL0001/URL0001_aunfold.sca", Weight=100 }
INFO:     },
INFO:     UniformScale=0.15999999642372,
INFO:     WarpInEffect={
INFO:       HideBones={ "Back_Upgrade", "Right_Upgrade" },
INFO:       PhaseShieldMesh="/units/url0001/URL0001_PhaseShield_mesh"
INFO:     }
INFO:   },
INFO:   Economy={
INFO:     BuildCostEnergy=5000000,
INFO:     BuildCostMass=2000,
INFO:     BuildRate=10,
INFO:     BuildTime=6000000,
INFO:     BuildableCategory={
INFO:       "BUILTBYCOMMANDER CYBRAN",
INFO:       "BUILTBYTIER2COMMANDER CYBRAN",
INFO:       "BUILTBYTIER3COMMANDER CYBRAN",
INFO:       "URL0001UPGRADE"
INFO:     },
INFO:     InitialRallyX=0,
INFO:     InitialRallyZ=5,
INFO:     MaintenanceConsumptionPerSecondEnergy=0,
INFO:     MaxBuildDistance=10,
INFO:     NaturalProducer=true,
INFO:     NeedToFaceTargetToBuild=false,
INFO:     ProductionPerSecondEnergy=20,
INFO:     ProductionPerSecondMass=1,
INFO:     RebuildBonusIds={ },
INFO:     SacrificeEnergyMult=0,
INFO:     SacrificeMassMult=0,
INFO:     StorageEnergy=4000,
INFO:     StorageMass=650,
INFO:     TeleportEnergyMod=0.029999999329448,
INFO:     TeleportMassMod=0,
INFO:     TeleportTimeMod=9.9999997473788e-005
INFO:   },
INFO:   Enhancements={
INFO:     AdvancedEngineering={
INFO:       BuildCostEnergy=21000,
INFO:       BuildCostMass=800,
INFO:       BuildTime=1000,
INFO:       BuildableCategoryAdds="BUILTBYTIER2COMMANDER CYBRAN",
INFO:       Icon="aes",
INFO:       Name="<LOC enhancements_0077>Tech 2 Engineering Suite",
INFO:       NewBuildRate=42,
INFO:       NewHealth=2000,
INFO:       NewRegenRate=10,
INFO:       ShowBones={ "Right_Upgrade" },
INFO:       Slot="LCH",
INFO:       UpgradeEffectBones={ "Right_Upgrade", "Right_Turret", "Right_Muzzle_02" },
INFO:       UpgradeUnitAmbientBones={ "URL0001" }
INFO:     },
INFO:     AdvancedEngineeringRemove={
INFO:       BuildCostEnergy=1,
INFO:       BuildCostMass=1,
INFO:       BuildTime=0.10000000149012,
INFO:       HideBones={ "Right_Upgrade" },
INFO:       Icon="aes",
INFO:       Name="<LOC enhancements_0078>Remove Engineering Suite",
INFO:       Prerequisite="AdvancedEngineering",
INFO:       RemoveEnhancements={ "AdvancedEngineering", "AdvancedEngineeringRemove" },
INFO:       Slot="LCH"
INFO:     },
INFO:     CloakingGenerator={
INFO:       BuildCostEnergy=750000,
INFO:       BuildCostMass=6000,
INFO:       BuildTime=4200,
INFO:       Icon="pcg",
INFO:       MaintenanceConsumptionPerSecondEnergy=3000,
INFO:       Name="<LOC enhancements_0079>Personal Cloaking Generator",
INFO:       NewHealth=15000,
INFO:       Prerequisite="StealthGenerator",
INFO:       Slot="Back",
INFO:       UpgradeUnitAmbientBones={ "URL0001" }
INFO:     },
INFO:     CloakingGeneratorRemove={
INFO:       BuildCostEnergy=1,
INFO:       BuildCostMass=1,
INFO:       BuildTime=1,
INFO:       Icon="pcg",
INFO:       Name="<LOC enhancements_0080>Remove Personal Cloaking Generator",
INFO:       Prerequisite="CloakingGenerator",
INFO:       RemoveEnhancements={
INFO:         "StealthGenerator",
INFO:         "CloakingGenerator",
INFO:         "CloakingGeneratorRemove"
INFO:       },
INFO:       Slot="Back"
INFO:     },
INFO:     CoolingUpgrade={
INFO:       BuildCostEnergy=24000,
INFO:       BuildCostMass=800,
INFO:       BuildTime=800,
INFO:       Icon="acu",
INFO:       Name="<LOC enhancements_0081>Microwave Accelerator",
INFO:       NewMaxRadius=30,
INFO:       NewRateOfFire=2,
INFO:       ShowBones={ "Right_Upgrade" },
INFO:       Slot="LCH",
INFO:       UpgradeEffectBones={ "Right_Upgrade", "Right_Turret", "Right_Muzzle_02" },
INFO:       UpgradeUnitAmbientBones={ "URL0001" }
INFO:     },
INFO:     CoolingUpgradeRemove={
INFO:       BuildCostEnergy=1,
INFO:       BuildCostMass=1,
INFO:       BuildTime=0.10000000149012,
INFO:       HideBones={ "Right_Upgrade" },
INFO:       Icon="acu",
INFO:       Name="<LOC enhancements_0082>Remove Microwave Accelerator",
INFO:       Prerequisite="CoolingUpgrade",
INFO:       RemoveEnhancements={ "CoolingUpgrade", "CoolingUpgradeRemove" },
INFO:       Slot="LCH"
INFO:     },
INFO:     MicrowaveLaserGenerator={
INFO:       BuildCostEnergy=500000,
INFO:       BuildCostMass=4000,
INFO:       BuildTime=2800,
INFO:       HideBones={ "Chest_Right", "Chest_Left" },
INFO:       Icon="mlg",
INFO:       Name="<LOC enhancements_0083>Microwave Laser Generator",
INFO:       Slot="RCH",
INFO:       UpgradeEffectBones={ "Chest_Right", "Chest_Left" },
INFO:       UpgradeUnitAmbientBones={ "URL0001" }
INFO:     },
INFO:     MicrowaveLaserGeneratorRemove={
INFO:       BuildCostEnergy=1,
INFO:       BuildCostMass=1,
INFO:       BuildTime=10,
INFO:       HideBones={ "Back_Upgrade" },
INFO:       Icon="mlg",
INFO:       Name="<LOC enhancements_0084>Remove Microwave Laser Generator",
INFO:       Prerequisite="MicrowaveLaserGenerator",
INFO:       RemoveEnhancements={
INFO:         "MicrowaveLaserGenerator",
INFO:         "MicrowaveLaserGeneratorRemove"
INFO:       },
INFO:       ShowBones={ "Chest_Right", "Chest_Left" },
INFO:       Slot="RCH"
INFO:     },
INFO:     NaniteTorpedoTube={
INFO:       BuildCostEnergy=37500,
INFO:       BuildCostMass=1500,
INFO:       BuildTime=1500,
INFO:       HideBones={ "Chest_Right", "Chest_Left" },
INFO:       Icon="ntt",
INFO:       Name="<LOC enhancements_0085>Nanite Torpedo Launcher",
INFO:       Slot="RCH",
INFO:       UpgradeEffectBones={ "Chest_Right", "Chest_Left" },
INFO:       UpgradeUnitAmbientBones={ "URL0001" }
INFO:     },
INFO:     NaniteTorpedoTubeRemove={
INFO:       BuildCostEnergy=1,
INFO:       BuildCostMass=1,
INFO:       BuildTime=10,
INFO:       Icon="ntt",
INFO:       Name="<LOC enhancements_0086>Remove Nanite Torpedo Launcher",
INFO:       Prerequisite="NaniteTorpedoTube",
INFO:       RemoveEnhancements={ "NaniteTorpedoTube", "NaniteTorpedoTubeRemove" },
INFO:       ShowBones={ "Chest_Right", "Chest_Left" },
INFO:       Slot="RCH"
INFO:     },
INFO:     ResourceAllocation={
INFO:       BuildCostEnergy=175000,
INFO:       BuildCostMass=5000,
INFO:       BuildTime=2800,
INFO:       Icon="ras",
INFO:       Name="<LOC enhancements_0087>Resource Allocation System",
INFO:       ProductionPerSecondEnergy=2700,
INFO:       ProductionPerSecondMass=12,
INFO:       ShowBones={ "Back_Upgrade" },
INFO:       Slot="Back",
INFO:       UpgradeEffectBones={ "Right_Arm_B01", "Left_Arm_B01", "Back_Upgrade" },
INFO:       UpgradeUnitAmbientBones={ "URL0001" }
INFO:     },
INFO:     ResourceAllocationRemove={
INFO:       BuildCostEnergy=1,
INFO:       BuildCostMass=1,
INFO:       BuildTime=0.10000000149012,
INFO:       HideBones={ "Back_Upgrade" },
INFO:       Icon="ras",
INFO:       Name="<LOC enhancements_0088>Remove Resource Allocation System",
INFO:       Prerequisite="ResourceAllocation",
INFO:       RemoveEnhancements={ "ResourceAllocation", "ResourceAllocationRemove" },
INFO:       Slot="Back"
INFO:     },
INFO:     Slots={
INFO:       Back={ name="<LOC _Back>", x=0, y=-10 },
INFO:       LCH={ name="<LOC _LCH>", x=60, y=2 },
INFO:       RCH={ name="<LOC _RCH>", x=-16, y=0 }
INFO:     },
INFO:     StealthGenerator={
INFO:       BuildCostEnergy=5000,
INFO:       BuildCostMass=350,
INFO:       BuildTime=500,
INFO:       Icon="psg",
INFO:       MaintenanceConsumptionPerSecondEnergy=50,
INFO:       Name="<LOC enhancements_0101>Personal Stealth Generator",
INFO:       ShowBones={ "Back_Upgrade" },
INFO:       Slot="Back",
INFO:       UpgradeEffectBones={ "Right_Arm_B01", "Left_Arm_B01", "Back_Upgrade" }
INFO:     },
INFO:     StealthGeneratorRemove={
INFO:       BuildCostEnergy=1,
INFO:       BuildCostMass=1,
INFO:       BuildTime=10,
INFO:       HideBones={ "Back_Upgrade" },
INFO:       Icon="psg",
INFO:       Name="<LOC enhancements_0102>Remove Personal Stealth Generator",
INFO:       Prerequisite="StealthGenerator",
INFO:       RemoveEnhancements={ "StealthGenerator", "StealthGeneratorRemove" },
INFO:       Slot="Back"
INFO:     },
INFO:     T3Engineering={
INFO:       BuildCostEnergy=50000,
INFO:       BuildCostMass=2400,
INFO:       BuildTime=8400,
INFO:       BuildableCategoryAdds="BUILTBYTIER3COMMANDER CYBRAN",
INFO:       Icon="ees",
INFO:       Name="<LOC enhancements_0103>Tech 3 Engineering Suite",
INFO:       NewBuildRate=100,
INFO:       NewHealth=3500,
INFO:       NewRegenRate=20,
INFO:       Prerequisite="AdvancedEngineering",
INFO:       Slot="LCH",
INFO:       UpgradeEffectBones={ "Right_Upgrade", "Right_Turret", "Right_Muzzle_02" },
INFO:       UpgradeUnitAmbientBones={ "URL0001" }
INFO:     },
INFO:     T3EngineeringRemove={
INFO:       BuildCostEnergy=1,
INFO:       BuildCostMass=1,
INFO:       BuildTime=0.10000000149012,
INFO:       Icon="ees",
INFO:       Name="<LOC enhancements_0104>Remove Tech 3 Engineering Suite",
INFO:       Prerequisite="T3Engineering",
INFO:       RemoveEnhancements={
INFO:         "AdvancedEngineering",
INFO:         "T3Engineering",
INFO:         "T3EngineeringRemove"
INFO:       },
INFO:       Slot="LCH"
INFO:     },
INFO:     Teleporter={
INFO:       BuildCostEnergy=1500000,
INFO:       BuildCostMass=15000,
INFO:       BuildTime=4200,
INFO:       Icon="pqt",
INFO:       MaintenanceConsumptionPerSecondEnergy=10000,
INFO:       Name="<LOC enhancements_0105>Personal Teleporter",
INFO:       ShowBones={ "Back_Upgrade" },
INFO:       Slot="Back",
INFO:       UpgradeEffectBones={ "Right_Arm_B01", "Left_Arm_B01", "Back_Upgrade" }
INFO:     },
INFO:     TeleporterRemove={
INFO:       BuildCostEnergy=1,
INFO:       BuildCostMass=1,
INFO:       BuildTime=0.10000000149012,
INFO:       HideBones={ "Back_Upgrade" },
INFO:       Icon="pqt",
INFO:       Name="<LOC enhancements_0106>Remove Personal Teleporter",
INFO:       Prerequisite="Teleporter",
INFO:       RemoveEnhancements={ "Teleporter", "TeleporterRemove" },
INFO:       Slot="Back"
INFO:     }
INFO:   },
INFO:   FactionCategory="CYBRAN",
INFO:   Footprint={
INFO:     Flags=0,
INFO:     MaxSlope=0.75,
INFO:     MinWaterDepth=0,
INFO:     OccupancyCaps=3,
INFO:     SizeX=1,
INFO:     SizeZ=1
INFO:   },
INFO:   General={
INFO:     BuildBones={
INFO:       AimBone=0,
INFO:       BuildEffectBones={ "Turret_Muzzle_01" },
INFO:       PitchBone="Left_Turret",
INFO:       YawBone="Torso"
INFO:     },
INFO:     CapCost=1,
INFO:     Category="Command",
INFO:     Classification="RULEUC_Commander",
INFO:     CommandCaps="1442559",
INFO:     FactionName="Cybran",
INFO:     Icon="amph",
INFO:     QuickSelectPriority=1,
INFO:     SeedUnit="",
INFO:     SelectionPriority=3,
INFO:     TechLevel="RULEUTL_Experimental",
INFO:     ToggleCaps="0",
INFO:     UnitWeight=1,
INFO:     UpgradesFrom="none",
INFO:     UpgradesFromBase="none",
INFO:     UpgradesTo=""
INFO:   },
INFO:   InertiaTensorX=0.52333337068558,
INFO:   InertiaTensorY=0.24000000953674,
INFO:   InertiaTensorZ=0.52333337068558,
INFO:   Intel={
INFO:     ActiveIntel={ Omni=true, Sonar=true },
INFO:     Cloak=true,
INFO:     CloakFieldRadius=0,
INFO:     FreeIntel=false,
INFO:     JamRadius={ Max=0, Min=0 },
INFO:     JammerBlips=0,
INFO:     OmniRadius=26,
INFO:     RadarRadius=0,
INFO:     RadarStealth=true,
INFO:     RadarStealthFieldRadius=0,
INFO:     ReactivateTime=2,
INFO:     ShowIntelOnSelect=false,
INFO:     SonarRadius=60,
INFO:     SonarStealth=true,
INFO:     SonarStealthFieldRadius=0,
INFO:     SpoofRadius={ Max=0, Min=0 },
INFO:     VisionRadius=26,
INFO:     WaterVisionRadius=26
INFO:   },
INFO:   Interface={ HelpText="<LOC url0001_help>Armored Command Unit" },
INFO:   LayerCategory="LAND",
INFO:   LifeBarHeight=0.15000000596046,
INFO:   LifeBarOffset=0.5,
INFO:   LifeBarRender=true,
INFO:   LifeBarSize=1.25,
INFO:   Physics={
INFO:     AltMotionType="RULEUMT_None",
INFO:     AttackElevation=0,
INFO:     BackUpDistance=3.6000001430511,
INFO:     BankingSlope=0,
INFO:     BuildOnLayerCaps="Land",
INFO:     BuildRestriction="RULEUBR_None",
INFO:     CatchUpAcc=1.7000000476837,
INFO:     DiveSurfaceSpeed=1,
INFO:     DragCoefficient=0.20000000298023,
INFO:     Elevation=0,
INFO:     FlattenSkirt=false,
INFO:     FuelRechargeRate=0,
INFO:     FuelUseTime=0,
INFO:     GroundCollisionOffset=0,
INFO:     LayerChangeOffsetHeight=-0.94999998807907,
INFO:     LayerTransitionDuration=0,
INFO:     MaxAcceleration=1.7000000476837,
INFO:     MaxBrake=0,
INFO:     MaxGroundVariation=1,
INFO:     MaxSpeed=1.7000000476837,
INFO:     MaxSpeedReverse=0,
INFO:     MaxSteerForce=12,
INFO:     MinSpeedPercent=0,
INFO:     MotionType="RULEUMT_Amphibious",
INFO:     OccupyRects={ },
INFO:     RaisedPlatforms={ },
INFO:     RollDamping=0.5,
INFO:     RollStability=0.20000000298023,
INFO:     RotateBodyWhileMoving=false,
INFO:     RotateOnSpot=false,
INFO:     RotateOnSpotThreshold=0.5,
INFO:     SinkLower=false,
INFO:     SkirtOffsetX=0,
INFO:     SkirtOffsetZ=0,
INFO:     SkirtSizeX=1,
INFO:     SkirtSizeZ=1,
INFO:     StandUpright=true,
INFO:     TurnFacingRate=0,
INFO:     TurnRadius=10,
INFO:     TurnRate=90,
INFO:     WobbleFactor=0,
INFO:     WobbleSpeed=0
INFO:   },
INFO:   RuntimeData={
INFO:     DownIconFileName="/textures/ui/common/icons/units/url0001_icon.dds",
INFO:     IconFileName="/textures/ui/common/icons/units/url0001_icon.dds",
INFO:     OverIconFileName="/textures/ui/common/icons/units/url0001_icon.dds",
INFO:     UpIconFileName="/textures/ui/common/icons/units/url0001_icon.dds"
INFO:   },
INFO:   ScriptClass="",
INFO:   ScriptModule="",
INFO:   SelectionCenterOffsetX=0,
INFO:   SelectionCenterOffsetY=0,
INFO:   SelectionCenterOffsetZ=-0.10000000149012,
INFO:   SelectionMeshScaleX=1,
INFO:   SelectionMeshScaleY=1,
INFO:   SelectionMeshScaleZ=1,
INFO:   SelectionMeshUseTopAmount=0,
INFO:   SelectionSizeX=0.69999998807907,
INFO:   SelectionSizeY=1,
INFO:   SelectionSizeZ=0.60000002384186,
INFO:   SelectionThickness=0.89999997615814,
INFO:   SelectionYOffset=0,
INFO:   SizeX=1.2000000476837,
INFO:   SizeY=2.2000000476837,
INFO:   SizeZ=1.2000000476837,
INFO:   Source="/units/url0001/url0001_unit.bp",
INFO:   StrategicIconName="icon_commander_generic",
INFO:   StrategicIconSortPriority=0,
INFO:   TechCategory="COMMAND",
INFO:   Transport={
INFO:     AirClass=false,
INFO:     CanFireFromTransport=false,
INFO:     Class2AttachSize=2,
INFO:     Class3AttachSize=6,
INFO:     Class4AttachSize=1,
INFO:     ClassGenericUpTo=0,
INFO:     ClassSAttachSize=0,
INFO:     DockingSlots=0,
INFO:     RepairRate=0,
INFO:     StorageSlots=0,
INFO:     TransportClass=3
INFO:   },
INFO:   UseOOBTestZoom=0,
INFO:   Veteran={ Level1=20, Level2=40, Level3=65, Level4=90, Level5=120 },
INFO:   VeteranHealingMult={
INFO:     0.10000000149012,
INFO:     0.20000000298023,
INFO:     0.30000001192093,
INFO:     0.40000000596046,
INFO:     0.5
INFO:   },
INFO:   VeteranMassMult=0.5,
INFO:   Weapon={
INFO:     {
INFO:       AboveWaterFireOnly=false,
INFO:       AboveWaterTargetsOnly=false,
INFO:       AimsStraightOnDisable=false,
INFO:       AlwaysRecheckTarget=true,
INFO:       AttackGroundTries=3,
INFO:       AutoInitiateAttackCommand=false,
INFO:       BallisticArc="RULEUBA_LowArc",
INFO:       BelowWaterFireOnly=false,
INFO:       BelowWaterTargetsOnly=false,
INFO:       BombDropThreshold=1.5,
INFO:       CannotAttackGround=false,
INFO:       CountedProjectile=false,
INFO:       Damage=0,
INFO:       DamageFriendly=false,
INFO:       DamageRadius=0,
INFO:       DamageType="Normal",
INFO:       DisplayName="",
INFO:       DummyWeapon=false,
INFO:       EffectiveRadius=-1,
INFO:       FireTargetLayerCapsTable={
INFO:         Land="Land|Water|Seabed",
INFO:         Seabed="Land|Water|Seabed",
INFO:         Water="Land|Water|Seabed"
INFO:       },
INFO:       FiringRandomness=0,
INFO:       FiringTolerance=0.0099999997764826,
INFO:       HeadingArcCenter=0,
INFO:       HeadingArcRange=180,
INFO:       IgnoreIfDisabled=false,
INFO:       IgnoresAlly=true,
INFO:       Label="DummyWeapon",
INFO:       LeadTarget=true,
INFO:       ManualFire=false,
INFO:       MaxHeightDiff=1.#INF,
INFO:       MaxProjectileStorage=0,
INFO:       MaxRadius=22,
INFO:       MaximumBeamLength=0,
INFO:       MinRadius=0,
INFO:       MuzzleVelocity=0,
INFO:       MuzzleVelocityRandom=0,
INFO:       MuzzleVelocityReduceDistance=0,
INFO:       NeedPrep=false,
INFO:       NeedToComputeBombDrop=false,
INFO:       NukeWeapon=false,
INFO:       OverChargeWeapon=false,
INFO:       PrefersPrimaryWeaponTarget=false,
INFO:       ProjectileId="",
INFO:       ProjectileLifetime=0,
INFO:       ProjectileLifetimeUsesMultiplier=0,
INFO:       RackBones={
INFO:         { MuzzleBones={ "Turret_Muzzle_02" }, RackBone="Right_Turret" }
INFO:       },
INFO:       RangeCategory="UWRC_Undefined",
INFO:       RateOfFire=0.5,
INFO:       ReTargetOnMiss=false,
INFO:       RequiresEnergy=0,
INFO:       RequiresMass=0,
INFO:       SlavedToBody=false,
INFO:       SlavedToBodyArcRange=1,
INFO:       StopOnPrimaryWeaponBusy=false,
INFO:       TargetCheckInterval=1,
INFO:       TargetPriorities={
INFO:         "SPECIALHIGHPRI",
INFO:         "MOBILE",
INFO:         "STRUCTURE DEFENSE",
INFO:         "SPECIALLOWPRI",
INFO:         "ALLUNITS"
INFO:       },
INFO:       TargetRestrictDisallow="UNTARGETABLE",
INFO:       TargetRestrictOnlyAllow="",
INFO:       TargetType="RULEWTT_Unit",
INFO:       TrackingRadius=1,
INFO:       TurretBoneMuzzle="Turret_Muzzle_02",
INFO:       TurretBonePitch="Right_Turret",
INFO:       TurretBoneYaw="Torso",
INFO:       TurretDualManipulators=false,
INFO:       TurretPitch=0,
INFO:       TurretPitchRange=90,
INFO:       TurretPitchSpeed=90,
INFO:       TurretYaw=0,
INFO:       TurretYawRange=180,
INFO:       TurretYawSpeed=90,
INFO:       Turreted=true,
INFO:       UIMaxRangeVisualId="",
INFO:       UIMinRangeVisualId="",
INFO:       UseFiringSolutionInsteadOfAimBone=true,
INFO:       YawOnlyOnTarget=false
INFO:     },
INFO:     {
INFO:       AboveWaterFireOnly=true,
INFO:       AboveWaterTargetsOnly=true,
INFO:       AimsStraightOnDisable=false,
INFO:       AlwaysRecheckTarget=true,
INFO:       AttackGroundTries=3,
INFO:       Audio={
INFO:         Fire=userdata: CSndParams* at 1FC48268 = [CSndParams at 0x15359B90]
INFO:       },
INFO:       AutoInitiateAttackCommand=false,
INFO:       BallisticArc="RULEUBA_LowArc",
INFO:       BelowWaterFireOnly=false,
INFO:       BelowWaterTargetsOnly=false,
INFO:       BombDropThreshold=1.5,
INFO:       CannotAttackGround=false,
INFO:       CollideFriendly=false,
INFO:       CountedProjectile=false,
INFO:       Damage=100,
INFO:       DamageRadius=0,
INFO:       DamageType="Normal",
INFO:       DisplayName="Molecular Ripper Cannon",
INFO:       DummyWeapon=false,
INFO:       EffectiveRadius=-1,
INFO:       FireTargetLayerCapsTable={
INFO:         Land="Land|Water|Seabed",
INFO:         Seabed="Land|Water|Seabed",
INFO:         Water="Land|Water|Seabed"
INFO:       },
INFO:       FiringRandomness=0,
INFO:       FiringTolerance=2,
INFO:       HeadingArcCenter=0,
INFO:       HeadingArcRange=180,
INFO:       IgnoreIfDisabled=false,
INFO:       IgnoresAlly=true,
INFO:       Label="RightRipper",
INFO:       LeadTarget=true,
INFO:       ManualFire=false,
INFO:       MaxHeightDiff=1.#INF,
INFO:       MaxProjectileStorage=0,
INFO:       MaxRadius=22,
INFO:       MaximumBeamLength=0,
INFO:       MinRadius=1,
INFO:       MuzzleSalvoDelay=0,
INFO:       MuzzleSalvoSize=1,
INFO:       MuzzleVelocity=35,
INFO:       MuzzleVelocityRandom=0,
INFO:       MuzzleVelocityReduceDistance=0,
INFO:       NeedPrep=false,
INFO:       NeedToComputeBombDrop=false,
INFO:       NukeWeapon=false,
INFO:       OverChargeWeapon=false,
INFO:       PrefersPrimaryWeaponTarget=false,
INFO:       ProjectileId="/projectiles/cdfcannonmolecular01/cdfcannonmolecular01_proj.bp",
INFO:       ProjectileLifetime=0,
INFO:       ProjectileLifetimeUsesMultiplier=2,
INFO:       ProjectilesPerOnFire=1,
INFO:       RackBones={
INFO:         { MuzzleBones={ "Turret_Muzzle_02" }, RackBone="Right_Turret" }
INFO:       },
INFO:       RackFireTogether=false,
INFO:       RackRecoilDistance=0,
INFO:       RackReloadTimeout=0,
INFO:       RackSalvoChargeTime=0,
INFO:       RackSalvoFiresAfterCharge=false,
INFO:       RackSalvoReloadTime=0,
INFO:       RackSalvoSize=1,
INFO:       RackSlavedToTurret=false,
INFO:       RangeCategory="UWRC_DirectFire",
INFO:       RateOfFire=1,
INFO:       ReTargetOnMiss=false,
INFO:       RequiresEnergy=0,
INFO:       RequiresMass=0,
INFO:       SlavedToBody=false,
INFO:       SlavedToBodyArcRange=1,
INFO:       StopOnPrimaryWeaponBusy=false,
INFO:       TargetCheckInterval=0.5,
INFO:       TargetPriorities={
INFO:         "SPECIALHIGHPRI",
INFO:         "MOBILE",
INFO:         "COMMAND",
INFO:         "STRUCTURE DEFENSE",
INFO:         "SPECIALLOWPRI",
INFO:         "ALLUNITS"
INFO:       },
INFO:       TargetRestrictDisallow="UNTARGETABLE",
INFO:       TargetRestrictOnlyAllow="",
INFO:       TargetType="RULEWTT_Unit",
INFO:       TrackingRadius=1,
INFO:       TurretBoneMuzzle="Turret_Muzzle_02",
INFO:       TurretBonePitch="Right_Turret",
INFO:       TurretBoneYaw="Torso",
INFO:       TurretDualManipulators=false,
INFO:       TurretPitch=0,
INFO:       TurretPitchRange=90,
INFO:       TurretPitchSpeed=90,
INFO:       TurretYaw=0,
INFO:       TurretYawRange=180,
INFO:       TurretYawSpeed=90,
INFO:       Turreted=true,
INFO:       UIMaxRangeVisualId="",
INFO:       UIMinRangeVisualId="",
INFO:       UseFiringSolutionInsteadOfAimBone=true,
INFO:       WeaponCategory="Direct Fire",
INFO:       YawOnlyOnTarget=false
INFO:     },
INFO:     {
INFO:       AboveWaterFireOnly=true,
INFO:       AboveWaterTargetsOnly=true,
INFO:       AimsStraightOnDisable=false,
INFO:       AlwaysRecheckTarget=true,
INFO:       AttackGroundTries=3,
INFO:       Audio={
INFO:         Fire=userdata: CSndParams* at 1FC4827C = [CSndParams at 0x15359B90]
INFO:       },
INFO:       AutoInitiateAttackCommand=false,
INFO:       BallisticArc="RULEUBA_None",
INFO:       BeamCollisionDelay=0.20000000298023,
INFO:       BeamLifetime=0.40000000596046,
INFO:       BelowWaterFireOnly=false,
INFO:       BelowWaterTargetsOnly=false,
INFO:       BombDropThreshold=1.5,
INFO:       CannotAttackGround=false,
INFO:       CollideFriendly=false,
INFO:       CountedProjectile=false,
INFO:       Damage=12000,
INFO:       DamageFriendly=false,
INFO:       DamageRadius=2.5,
INFO:       DamageType="Overcharge",
INFO:       DisplayName="Overcharge Cannon",
INFO:       DummyWeapon=false,
INFO:       EffectiveRadius=-1,
INFO:       EnergyChargeForFirstShot=false,
INFO:       EnergyDrainPerSecond=5000,
INFO:       EnergyRequired=5000,
INFO:       FireTargetLayerCapsTable={
INFO:         Land="Land|Water|Seabed",
INFO:         Seabed="Land|Water|Seabed",
INFO:         Water="Land|Water|Seabed"
INFO:       },
INFO:       FiringRandomness=0,
INFO:       FiringTolerance=2,
INFO:       HeadingArcCenter=0,
INFO:       HeadingArcRange=180,
INFO:       IgnoreIfDisabled=false,
INFO:       IgnoresAlly=true,
INFO:       Label="OverCharge",
INFO:       LeadTarget=true,
INFO:       ManualFire=true,
INFO:       MaxHeightDiff=1.#INF,
INFO:       MaxProjectileStorage=0,
INFO:       MaxRadius=22,
INFO:       MaximumBeamLength=0,
INFO:       MinRadius=0,
INFO:       MuzzleSalvoDelay=0,
INFO:       MuzzleSalvoSize=1,
INFO:       MuzzleVelocity=25,
INFO:       MuzzleVelocityRandom=0,
INFO:       MuzzleVelocityReduceDistance=0,
INFO:       NeedPrep=false,
INFO:       NeedToComputeBombDrop=false,
INFO:       NukeWeapon=false,
INFO:       OverChargeWeapon=true,
INFO:       PrefersPrimaryWeaponTarget=false,
INFO:       ProjectileId="/projectiles/cdfcannonmolecularovercharge01/cdfcannonmolecularovercharge01_proj.bp",
INFO:       ProjectileLifetime=0,
INFO:       ProjectileLifetimeUsesMultiplier=2,
INFO:       ProjectilesPerOnFire=1,
INFO:       RackBones={
INFO:         { MuzzleBones={ "Turret_Muzzle_02" }, RackBone="Right_Turret" }
INFO:       },
INFO:       RackFireTogether=false,
INFO:       RackRecoilDistance=0,
INFO:       RackReloadTimeout=10,
INFO:       RackSalvoChargeTime=0,
INFO:       RackSalvoFiresAfterCharge=false,
INFO:       RackSalvoReloadTime=0,
INFO:       RackSalvoSize=1,
INFO:       RackSlavedToTurret=false,
INFO:       RangeCategory="UWRC_DirectFire",
INFO:       RateOfFire=0.30000001192093,
INFO:       ReTargetOnMiss=false,
INFO:       RequiresEnergy=0,
INFO:       RequiresMass=0,
INFO:       SlavedToBody=false,
INFO:       SlavedToBodyArcRange=1,
INFO:       StopOnPrimaryWeaponBusy=false,
INFO:       TargetCheckInterval=0.10000000149012,
INFO:       TargetPriorities={
INFO:         "SPECIALHIGHPRI",
INFO:         "MOBILE EXPERIMENTAL",
INFO:         "MOBILE TECH3",
INFO:         "MOBILE TECH2",
INFO:         "MOBILE TECH1",
INFO:         "COMMAND",
INFO:         "STRUCTURE DEFENSE",
INFO:         "SPECIALLOWPRI",
INFO:         "ALLUNITS"
INFO:       },
INFO:       TargetRestrictDisallow="UNTARGETABLE",
INFO:       TargetRestrictOnlyAllow="",
INFO:       TargetType="RULEWTT_Unit",
INFO:       TrackingRadius=1,
INFO:       TurretBoneMuzzle="Turret_Muzzle_02",
INFO:       TurretBonePitch="Right_Turret",
INFO:       TurretBoneYaw="Torso",
INFO:       TurretDualManipulators=false,
INFO:       TurretPitch=0,
INFO:       TurretPitchRange=80,
INFO:       TurretPitchSpeed=90,
INFO:       TurretYaw=0,
INFO:       TurretYawRange=180,
INFO:       TurretYawSpeed=90,
INFO:       Turreted=true,
INFO:       UIMaxRangeVisualId="",
INFO:       UIMinRangeVisualId="",
INFO:       UseFiringSolutionInsteadOfAimBone=true,
INFO:       WeaponCategory="Direct Fire",
INFO:       YawOnlyOnTarget=false
INFO:     },
INFO:     {
INFO:       AboveWaterFireOnly=true,
INFO:       AboveWaterTargetsOnly=true,
INFO:       AimsStraightOnDisable=false,
INFO:       AlwaysRecheckTarget=true,
INFO:       AttackGroundTries=3,
INFO:       Audio={
INFO:         Fire=userdata: CSndParams* at 1FC48290 = [CSndParams at 0x15359B90]
INFO:       },
INFO:       AutoInitiateAttackCommand=false,
INFO:       BallisticArc="RULEUBA_None",
INFO:       BeamCollisionDelay=0.20000000298023,
INFO:       BeamLifetime=0.40000000596046,
INFO:       BelowWaterFireOnly=false,
INFO:       BelowWaterTargetsOnly=false,
INFO:       BombDropThreshold=1.5,
INFO:       CannotAttackGround=false,
INFO:       CollideFriendly=false,
INFO:       CountedProjectile=false,
INFO:       Damage=12000,
INFO:       DamageFriendly=false,
INFO:       DamageRadius=2.5,
INFO:       DamageType="Overcharge",
INFO:       DisplayName="Overcharge Cannon",
INFO:       DummyWeapon=false,
INFO:       EffectiveRadius=-1,
INFO:       EnergyChargeForFirstShot=false,
INFO:       EnergyDrainPerSecond=5000,
INFO:       EnergyRequired=5000,
INFO:       FireTargetLayerCapsTable={
INFO:         Land="Land|Water|Seabed",
INFO:         Seabed="Land|Water|Seabed",
INFO:         Water="Land|Water|Seabed"
INFO:       },
INFO:       FiringRandomness=0,
INFO:       FiringTolerance=2,
INFO:       HeadingArcCenter=0,
INFO:       HeadingArcRange=180,
INFO:       IgnoreIfDisabled=false,
INFO:       IgnoresAlly=true,
INFO:       Label="AutoOverCharge",
INFO:       LeadTarget=true,
INFO:       ManualFire=false,
INFO:       MaxHeightDiff=1.#INF,
INFO:       MaxProjectileStorage=0,
INFO:       MaxRadius=22,
INFO:       MaximumBeamLength=0,
INFO:       MinRadius=0,
INFO:       MuzzleSalvoDelay=0,
INFO:       MuzzleSalvoSize=1,
INFO:       MuzzleVelocity=25,
INFO:       MuzzleVelocityRandom=0,
INFO:       MuzzleVelocityReduceDistance=0,
INFO:       NeedPrep=false,
INFO:       NeedToComputeBombDrop=false,
INFO:       NukeWeapon=false,
INFO:       OverChargeWeapon=false,
INFO:       PrefersPrimaryWeaponTarget=false,
INFO:       ProjectileId="/projectiles/cdfcannonmolecularovercharge01/cdfcannonmolecularovercharge01_proj.bp",
INFO:       ProjectileLifetime=0,
INFO:       ProjectileLifetimeUsesMultiplier=2,
INFO:       ProjectilesPerOnFire=1,
INFO:       RackBones={
INFO:         { MuzzleBones={ "Turret_Muzzle_02" }, RackBone="Right_Turret" }
INFO:       },
INFO:       RackFireTogether=false,
INFO:       RackRecoilDistance=0,
INFO:       RackReloadTimeout=10,
INFO:       RackSalvoChargeTime=0,
INFO:       RackSalvoFiresAfterCharge=false,
INFO:       RackSalvoReloadTime=0,
INFO:       RackSalvoSize=1,
INFO:       RackSlavedToTurret=false,
INFO:       RangeCategory="UWRC_DirectFire",
INFO:       RateOfFire=0.20000000298023,
INFO:       ReTargetOnMiss=false,
INFO:       RequiresEnergy=0,
INFO:       RequiresMass=0,
INFO:       SlavedToBody=false,
INFO:       SlavedToBodyArcRange=1,
INFO:       StopOnPrimaryWeaponBusy=false,
INFO:       TargetCheckInterval=0.10000000149012,
INFO:       TargetPriorities={
INFO:         "SPECIALHIGHPRI",
INFO:         "MOBILE EXPERIMENTAL",
INFO:         "MOBILE TECH3",
INFO:         "MOBILE TECH2",
INFO:         "MOBILE TECH1",
INFO:         "COMMAND",
INFO:         "STRUCTURE DEFENSE",
INFO:         "SPECIALLOWPRI",
INFO:         "ALLUNITS"
INFO:       },
INFO:       TargetRestrictDisallow="UNTARGETABLE",
INFO:       TargetRestrictOnlyAllow="",
INFO:       TargetType="RULEWTT_Unit",
INFO:       TrackingRadius=1,
INFO:       TurretBoneMuzzle="Turret_Muzzle_02",
INFO:       TurretBonePitch="Right_Turret",
INFO:       TurretBoneYaw="Torso",
INFO:       TurretDualManipulators=false,
INFO:       TurretPitch=0,
INFO:       TurretPitchRange=80,
INFO:       TurretPitchSpeed=90,
INFO:       TurretYaw=0,
INFO:       TurretYawRange=180,
INFO:       TurretYawSpeed=90,
INFO:       Turreted=true,
INFO:       UIMaxRangeVisualId="",
INFO:       UIMinRangeVisualId="",
INFO:       UseFiringSolutionInsteadOfAimBone=true,
INFO:       WeaponCategory="Direct Fire",
INFO:       YawOnlyOnTarget=false
INFO:     },
INFO:     {
INFO:       AboveWaterFireOnly=false,
INFO:       AboveWaterTargetsOnly=true,
INFO:       AimsStraightOnDisable=false,
INFO:       AlwaysRecheckTarget=true,
INFO:       AttackGroundTries=3,
INFO:       AutoInitiateAttackCommand=false,
INFO:       BallisticArc="RULEUBA_None",
INFO:       BelowWaterFireOnly=false,
INFO:       BelowWaterTargetsOnly=false,
INFO:       BombDropThreshold=1.5,
INFO:       CannotAttackGround=false,
INFO:       CollideFriendly=false,
INFO:       CountedProjectile=false,
INFO:       Damage=0,
INFO:       DamageFriendly=true,
INFO:       DamageRadius=0,
INFO:       DamageType="Deathnuke",
INFO:       DisplayName="Death Nuke",
INFO:       DummyWeapon=false,
INFO:       EffectiveRadius=-1,
INFO:       FireOnDeath=true,
INFO:       FiringRandomness=0,
INFO:       FiringTolerance=2,
INFO:       HeadingArcCenter=0,
INFO:       HeadingArcRange=180,
INFO:       IgnoreIfDisabled=false,
INFO:       IgnoresAlly=true,
INFO:       Label="DeathWeapon",
INFO:       LeadTarget=true,
INFO:       ManualFire=false,
INFO:       MaxHeightDiff=1.#INF,
INFO:       MaxProjectileStorage=0,
INFO:       MaxRadius=1,
INFO:       MaximumBeamLength=0,
INFO:       MinRadius=0,
INFO:       MuzzleSalvoDelay=0,
INFO:       MuzzleSalvoSize=1,
INFO:       MuzzleVelocity=0,
INFO:       MuzzleVelocityRandom=0,
INFO:       MuzzleVelocityReduceDistance=0,
INFO:       NeedPrep=false,
INFO:       NeedToComputeBombDrop=false,
INFO:       NukeInnerRingDamage=2000,
INFO:       NukeInnerRingRadius=30,
INFO:       NukeInnerRingTicks=24,
INFO:       NukeInnerRingTotalTime=0,
INFO:       NukeOuterRingDamage=500,
INFO:       NukeOuterRingRadius=40,
INFO:       NukeOuterRingTicks=20,
INFO:       NukeOuterRingTotalTime=0,
INFO:       NukeWeapon=false,
INFO:       OverChargeWeapon=false,
INFO:       PrefersPrimaryWeaponTarget=false,
INFO:       ProjectileId="/projectiles/cifempfluxwarhead02/cifempfluxwarhead02_proj.bp",
INFO:       ProjectileLifetime=0,
INFO:       ProjectileLifetimeUsesMultiplier=0,
INFO:       RackBones={ { MuzzleBones={ 0 }, RackBone=0 } },
INFO:       RackRecoilDistance=0,
INFO:       RangeCategory="UWRC_Undefined",
INFO:       RateOfFire=1,
INFO:       ReTargetOnMiss=false,
INFO:       RequiresEnergy=0,
INFO:       RequiresMass=0,
INFO:       SlavedToBody=false,
INFO:       SlavedToBodyArcRange=1,
INFO:       StopOnPrimaryWeaponBusy=false,
INFO:       TargetCheckInterval=9999999,
INFO:       TargetRestrictDisallow="UNTARGETABLE",
INFO:       TargetRestrictOnlyAllow="",
INFO:       TargetType="RULEWTT_Unit",
INFO:       TrackingRadius=1,
INFO:       Turreted=false,
INFO:       UIMaxRangeVisualId="",
INFO:       UIMinRangeVisualId="",
INFO:       UseFiringSolutionInsteadOfAimBone=false,
INFO:       WeaponCategory="Death",
INFO:       YawOnlyOnTarget=false
INFO:     },
INFO:     {
INFO:       AboveWaterFireOnly=true,
INFO:       AboveWaterTargetsOnly=true,
INFO:       AimsStraightOnDisable=false,
INFO:       AlwaysRecheckTarget=true,
INFO:       AttackGroundTries=3,
INFO:       Audio={
INFO:         BeamLoop=userdata: CSndParams* at 1FC485B0 = [CSndParams at 0x15359FA0],
INFO:         BeamStart=userdata: CSndParams* at 1FC482E0 = [CSndParams at 0x15359640],
INFO:         BeamStop=userdata: CSndParams* at 1FC482F4 = [CSndParams at 0x153596E0],
INFO:         Unpack=userdata: CSndParams* at 1FC48600 = [CSndParams at 0x15359780]
INFO:       },
INFO:       AutoInitiateAttackCommand=false,
INFO:       BallisticArc="RULEUBA_None",
INFO:       BeamCollisionDelay=0,
INFO:       BeamLifetime=0,
INFO:       BelowWaterFireOnly=false,
INFO:       BelowWaterTargetsOnly=false,
INFO:       BombDropThreshold=1.5,
INFO:       CanFireFromTransport=true,
INFO:       CannotAttackGround=false,
INFO:       CollideFriendly=false,
INFO:       ContinuousBeam=true,
INFO:       CountedProjectile=false,
INFO:       Damage=400,
INFO:       DamageRadius=0.5,
INFO:       DamageType="Normal",
INFO:       DisplayName="Heavy Microwave Laser",
INFO:       DummyWeapon=false,
INFO:       EffectiveRadius=-1,
INFO:       EnabledByEnhancement="MicrowaveLaserGenerator",
INFO:       EnergyChargeForFirstShot=false,
INFO:       FireTargetLayerCapsTable={
INFO:         Land="Land|Water|Seabed",
INFO:         Seabed="Land|Water|Seabed",
INFO:         Water="Land|Water|Seabed"
INFO:       },
INFO:       FiringRandomness=0,
INFO:       FiringTolerance=0.25,
INFO:       HeadingArcCenter=0,
INFO:       HeadingArcRange=180,
INFO:       IgnoreIfDisabled=false,
INFO:       IgnoresAlly=true,
INFO:       Label="MLG",
INFO:       LeadTarget=true,
INFO:       ManualFire=false,
INFO:       MaxHeightDiff=1.#INF,
INFO:       MaxProjectileStorage=0,
INFO:       MaxRadius=22,
INFO:       MaximumBeamLength=0,
INFO:       MinRadius=0,
INFO:       MuzzleChargeDelay=0,
INFO:       MuzzleSalvoDelay=0,
INFO:       MuzzleSalvoSize=1,
INFO:       MuzzleVelocity=0,
INFO:       MuzzleVelocityRandom=0,
INFO:       MuzzleVelocityReduceDistance=0,
INFO:       NeedPrep=false,
INFO:       NeedToComputeBombDrop=false,
INFO:       NukeWeapon=false,
INFO:       OverChargeWeapon=false,
INFO:       PrefersPrimaryWeaponTarget=true,
INFO:       ProjectileId="",
INFO:       ProjectileLifetime=0,
INFO:       ProjectileLifetimeUsesMultiplier=0,
INFO:       ProjectilesPerOnFire=1,
INFO:       RackBones={
INFO:         { MuzzleBones={ "Center_Turret" }, RackBone="Center_Turret" }
INFO:       },
INFO:       RackFireTogether=false,
INFO:       RackRecoilDistance=0,
INFO:       RackReloadTimeout=1,
INFO:       RackSalvoChargeTime=0,
INFO:       RackSalvoReloadTime=0,
INFO:       RackSalvoSize=1,
INFO:       RackSlavedToTurret=false,
INFO:       RangeCategory="UWRC_DirectFire",
INFO:       RateOfFire=10,
INFO:       ReTargetOnMiss=false,
INFO:       RequiresEnergy=0,
INFO:       RequiresMass=0,
INFO:       SlavedToBody=false,
INFO:       SlavedToBodyArcRange=1,
INFO:       StopOnPrimaryWeaponBusy=false,
INFO:       TargetCheckInterval=0.10000000149012,
INFO:       TargetPriorities={
INFO:         "SPECIALHIGHPRI",
INFO:         "MOBILE",
INFO:         "STRUCTURE DEFENSE",
INFO:         "SPECIALLOWPRI",
INFO:         "ALLUNITS"
INFO:       },
INFO:       TargetRestrictDisallow="UNTARGETABLE",
INFO:       TargetRestrictOnlyAllow="",
INFO:       TargetType="RULEWTT_Unit",
INFO:       TrackingRadius=1.1499999761581,
INFO:       TurretBoneMuzzle="Center_Turret",
INFO:       TurretBonePitch="Center_Turret",
INFO:       TurretBoneYaw="Center_Turret",
INFO:       TurretDualManipulators=false,
INFO:       TurretPitch=0,
INFO:       TurretPitchRange=80,
INFO:       TurretPitchSpeed=90,
INFO:       TurretYaw=0,
INFO:       TurretYawRange=10,
INFO:       TurretYawSpeed=110,
INFO:       Turreted=true,
INFO:       UIMaxRangeVisualId="",
INFO:       UIMinRangeVisualId="",
INFO:       UseFiringSolutionInsteadOfAimBone=true,
INFO:       WeaponCategory="Direct Fire Experimental",
INFO:       WeaponRepackTimeout=0,
INFO:       WeaponUnpacks=false,
INFO:       YawOnlyOnTarget=false
INFO:     },
INFO:     {
INFO:       AboveWaterFireOnly=false,
INFO:       AboveWaterTargetsOnly=false,
INFO:       AimsStraightOnDisable=false,
INFO:       AlwaysRecheckTarget=true,
INFO:       AttackGroundTries=3,
INFO:       AutoInitiateAttackCommand=false,
INFO:       BallisticArc="RULEUBA_None",
INFO:       BelowWaterFireOnly=true,
INFO:       BelowWaterTargetsOnly=false,
INFO:       BombDropThreshold=1.5,
INFO:       CannotAttackGround=false,
INFO:       CollideFriendly=false,
INFO:       CountedProjectile=false,
INFO:       Damage=250,
INFO:       DamageRadius=0,
INFO:       DamageType="Normal",
INFO:       DisplayName="Nanite Torpedo",
INFO:       DummyWeapon=false,
INFO:       EffectiveRadius=0,
INFO:       EnabledByEnhancement="NaniteTorpedoTube",
INFO:       FireTargetLayerCapsTable={ Seabed="Seabed|Sub|Water" },
INFO:       FiringRandomness=0,
INFO:       FiringTolerance=2,
INFO:       HeadingArcCenter=0,
INFO:       HeadingArcRange=180,
INFO:       IgnoreIfDisabled=false,
INFO:       IgnoresAlly=true,
INFO:       Label="Torpedo",
INFO:       LeadTarget=true,
INFO:       ManualFire=false,
INFO:       MaxHeightDiff=1.#INF,
INFO:       MaxProjectileStorage=0,
INFO:       MaxRadius=60,
INFO:       MaximumBeamLength=0,
INFO:       MinRadius=0,
INFO:       MuzzleSalvoDelay=0.80000001192093,
INFO:       MuzzleSalvoSize=4,
INFO:       MuzzleVelocity=5,
INFO:       MuzzleVelocityRandom=0,
INFO:       MuzzleVelocityReduceDistance=0,
INFO:       NeedPrep=false,
INFO:       NeedToComputeBombDrop=false,
INFO:       NukeWeapon=false,
INFO:       OverChargeWeapon=false,
INFO:       PrefersPrimaryWeaponTarget=false,
INFO:       ProjectileId="/projectiles/cantorpedonanite01/cantorpedonanite01_proj.bp",
INFO:       ProjectileLifetime=7,
INFO:       ProjectileLifetimeUsesMultiplier=0,
INFO:       ProjectilesPerOnFire=1,
INFO:       RackBones={
INFO:         { MuzzleBones={ "Center_Turret" }, RackBone="Center_Turret" }
INFO:       },
INFO:       RackFireTogether=false,
INFO:       RackRecoilDistance=0,
INFO:       RackReloadTimeout=10,
INFO:       RackSalvoChargeTime=0,
INFO:       RackSalvoReloadTime=0,
INFO:       RackSalvoSize=1,
INFO:       RackSlavedToTurret=false,
INFO:       RangeCategory="UWRC_AntiNavy",
INFO:       RateOfFire=0.25,
INFO:       ReTargetOnMiss=false,
INFO:       RequiresEnergy=0,
INFO:       RequiresMass=0,
INFO:       SlavedToBody=false,
INFO:       SlavedToBodyArcRange=1,
INFO:       StopOnPrimaryWeaponBusy=false,
INFO:       TargetCheckInterval=1,
INFO:       TargetPriorities={
INFO:         "SPECIALHIGHPRI",
INFO:         "MOBILE",
INFO:         "STRUCTURE DEFENSE",
INFO:         "SPECIALLOWPRI",
INFO:         "ALLUNITS"
INFO:       },
INFO:       TargetRestrictDisallow="UNTARGETABLE, HOVER",
INFO:       TargetRestrictOnlyAllow="",
INFO:       TargetType="RULEWTT_Unit",
INFO:       TrackingRadius=1,
INFO:       Turreted=false,
INFO:       UIMaxRangeVisualId="",
INFO:       UIMinRangeVisualId="",
INFO:       UseFiringSolutionInsteadOfAimBone=false,
INFO:       WeaponCategory="Anti Navy",
INFO:       YawOnlyOnTarget=false
INFO:     },
INFO:     {
INFO:       AboveWaterFireOnly=false,
INFO:       AboveWaterTargetsOnly=false,
INFO:       AimsStraightOnDisable=false,
INFO:       AlwaysRecheckTarget=true,
INFO:       AttackGroundTries=3,
INFO:       AutoInitiateAttackCommand=false,
INFO:       BallisticArc="RULEUBA_None",
INFO:       BelowWaterFireOnly=false,
INFO:       BelowWaterTargetsOnly=false,
INFO:       BombDropThreshold=1.5,
INFO:       CannotAttackGround=false,
INFO:       CountedProjectile=false,
INFO:       Damage=100,
INFO:       DamageFriendly=true,
INFO:       DamageRadius=4,
INFO:       DamageType="Normal",
INFO:       DisplayName="Teleport in",
INFO:       DummyWeapon=true,
INFO:       EffectiveRadius=-1,
INFO:       FiringRandomness=0,
INFO:       FiringTolerance=0.0099999997764826,
INFO:       HeadingArcCenter=0,
INFO:       HeadingArcRange=180,
INFO:       IgnoreIfDisabled=false,
INFO:       IgnoresAlly=true,
INFO:       Label="TeleportWeapon",
INFO:       LeadTarget=true,
INFO:       ManualFire=false,
INFO:       MaxHeightDiff=1.#INF,
INFO:       MaxProjectileStorage=0,
INFO:       MaxRadius=1,
INFO:       MaximumBeamLength=0,
INFO:       MinRadius=0,
INFO:       MuzzleVelocity=0,
INFO:       MuzzleVelocityRandom=0,
INFO:       MuzzleVelocityReduceDistance=0,
INFO:       NeedPrep=false,
INFO:       NeedToComputeBombDrop=false,
INFO:       NukeWeapon=false,
INFO:       OverChargeWeapon=false,
INFO:       PrefersPrimaryWeaponTarget=false,
INFO:       ProjectileId="",
INFO:       ProjectileLifetime=0,
INFO:       ProjectileLifetimeUsesMultiplier=0,
INFO:       RangeCategory="UWRC_Undefined",
INFO:       RateOfFire=1,
INFO:       ReTargetOnMiss=false,
INFO:       RequiresEnergy=0,
INFO:       RequiresMass=0,
INFO:       SlavedToBody=false,
INFO:       SlavedToBodyArcRange=1,
INFO:       StopOnPrimaryWeaponBusy=false,
INFO:       TargetCheckInterval=3,
INFO:       TargetRestrictDisallow="",
INFO:       TargetRestrictOnlyAllow="",
INFO:       TargetType="RULEWTT_Unit",
INFO:       TrackingRadius=1,
INFO:       Turreted=false,
INFO:       UIMaxRangeVisualId="",
INFO:       UIMinRangeVisualId="",
INFO:       UseFiringSolutionInsteadOfAimBone=false,
INFO:       WeaponCategory="Teleport",
INFO:       YawOnlyOnTarget=false
INFO:     }
INFO:   }
INFO: }
]]