name = "EcoManagementFramework"
uid = "d59cd1a3-961b-46c6-b915-b3b550b28513"
version = 1
copyright = "No"
description = "Set up for eco mods to work together to track effect of pausing or unpausing units on expected eco values"
author = "Thomas Young"
url = "upcoder.com"
selectable = true
enabled = true
exclusive = false
ui_only = true
requires = {}
requiresNames = {}
conflicts = {}
before = {}
after = {}
