name = "Throttle"
uid = "3ec155eb-3319-4ad5-9617-58d6afc5fcef"
version = 1
copyright = "no"
description = "Units can be marked as 'throttled', and then get paused based on come eco thresholds"
author = "Thomas Young"
url = "upcoder.com"
selectable = true
enabled = true
exclusive = false
ui_only = true
requires = {}
requiresNames = {}
conflicts = { }
before = {}
after = {}
