name = "UnitTracking"
uid = "e821a66d-8d73-442e-9df1-08d7516e4c17"
version = 1
copyright = "No"
description = "Alternative method of tracking all owned units"
author = "Thomas Young"
url = "upcoder.com"
selectable = true
enabled = true
exclusive = false
ui_only = true
requires = {}
requiresNames = {}
conflicts = {}
before = {}
after = {}
