name = "RangeRings"
version = 1
copyright = "no"
description = "Just the bit to show unit build and attack ranges, extracted from Additional Camera Stuff v3.2."
author = "Thomas Young"
url = "upcoder.com"
uid = "79775016-f295-451c-ae83-9ff71a21087b"
selectable = true
enabled = true
exclusive = false
ui_only = true
requires = {}
requiresNames = {}
conflicts = {}
before = {}
after = {}
